[theme]
primaryColor = "#1a5276"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
